// Auto-Generated by FAKE; do not edit
namespace System

open System.Reflection

[<assembly: AssemblyTitleAttribute("Partas.Solid")>]
[<assembly: AssemblyProductAttribute("Partas.Solid")>]
[<assembly: AssemblyVersionAttribute("2.0.0")>]
[<assembly: AssemblyFileVersionAttribute("2.0.0")>]
do ()

module internal AssemblyVersionInformation =
    [<Literal>]
    let AssemblyTitle = "Partas.Solid"

    [<Literal>]
    let AssemblyProduct = "Partas.Solid"

    [<Literal>]
    let AssemblyVersion = "2.0.0"

    [<Literal>]
    let AssemblyFileVersion = "2.0.0"
